//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace validation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universo_NC
    {
        public Nullable<double> TOP_PRODUCT { get; set; }
        public Nullable<double> L1 { get; set; }
        public Nullable<double> L2 { get; set; }
        public Nullable<double> L3 { get; set; }
        public string L4 { get; set; }
        public int ID { get; set; }
    }
}
